# Generated by Django 3.2.3 on 2021-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('groups', models.CharField(max_length=40)),
                ('permissions', models.CharField(max_length=40)),
            ],
        ),
    ]
